modLoader="javafml"
loaderVersion="[40,)"
license="The Unlicense"

[[mods]]
    modId="global_server_config"
    version="${file.jarVersion}"
    displayName="Global Server Config"
    authors="TJT01"
    description="Tiny mod that makes Forge load server configs from the same folder as client and common configs."

[[dependencies.global_server_config]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.global_server_config]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
